<?php

/**
 * @file
 * Contains \Netzstrategen\Ssofact\AlfaCountry.
 */

namespace Netzstrategen\Ssofact;

/**
 * Alfamedia VM country code mapping.
 */
class AlfaCountry {

  /**
   * Maps WooCommerce/ISO country codes to Alfamedia VM country vehicle codes (LKZ).
   *
   * @see woocommerce/i18n/countries.php
   */
  const MAP = [
    'AF' => 'AFG', // __( 'Afghanistan', 'woocommerce' ),
    'AX' => '', // __( '&#197;land Islands', 'woocommerce' ),
    'AL' => 'AL', // __( 'Albania', 'woocommerce' ),
    'DZ' => 'DZ', // __( 'Algeria', 'woocommerce' ),
    'AS' => '', // __( 'American Samoa', 'woocommerce' ),
    'AD' => '', // __( 'Andorra', 'woocommerce' ),
    'AO' => 'ANG', // __( 'Angola', 'woocommerce' ),
    'AI' => '', // __( 'Anguilla', 'woocommerce' ),
    'AQ' => '', // __( 'Antarctica', 'woocommerce' ),
    'AG' => '', // __( 'Antigua and Barbuda', 'woocommerce' ),
    'AR' => 'RA', // __( 'Argentina', 'woocommerce' ),
    'AM' => 'ARM', // __( 'Armenia', 'woocommerce' ),
    'AW' => '', // __( 'Aruba', 'woocommerce' ),
    'AU' => 'AUS', // __( 'Australia', 'woocommerce' ),
    'AT' => 'A', // __( 'Austria', 'woocommerce' ),
    'AZ' => '', // __( 'Azerbaijan', 'woocommerce' ),
    'BS' => '', // __( 'Bahamas', 'woocommerce' ),
    'BH' => '', // __( 'Bahrain', 'woocommerce' ),
    'BD' => '', // __( 'Bangladesh', 'woocommerce' ),
    'BB' => '', // __( 'Barbados', 'woocommerce' ),
    'BY' => 'BY', // __( 'Belarus', 'woocommerce' ),
    'BE' => 'B', // __( 'Belgium', 'woocommerce' ),
    'PW' => '', // __( 'Belau', 'woocommerce' ),
    'BZ' => '', // __( 'Belize', 'woocommerce' ),
    'BJ' => '', // __( 'Benin', 'woocommerce' ),
    'BM' => '', // __( 'Bermuda', 'woocommerce' ),
    'BT' => '', // __( 'Bhutan', 'woocommerce' ),
    'BO' => 'BOL', // __( 'Bolivia', 'woocommerce' ),
    'BQ' => '', // __( 'Bonaire, Saint Eustatius and Saba', 'woocommerce' ),
    'BA' => 'BIH', // __( 'Bosnia and Herzegovina', 'woocommerce' ),
    'BW' => '', // __( 'Botswana', 'woocommerce' ),
    'BV' => '', // __( 'Bouvet Island', 'woocommerce' ),
    'BR' => 'BR', // __( 'Brazil', 'woocommerce' ),
    'IO' => '', // __( 'British Indian Ocean Territory', 'woocommerce' ),
    'VG' => 'VG', // __( 'British Virgin Islands', 'woocommerce' ),
    'BN' => '', // __( 'Brunei', 'woocommerce' ),
    'BG' => 'BG', // __( 'Bulgaria', 'woocommerce' ),
    'BF' => '', // __( 'Burkina Faso', 'woocommerce' ),
    'BI' => '', // __( 'Burundi', 'woocommerce' ),
    'KH' => '', // __( 'Cambodia', 'woocommerce' ),
    'CM' => 'CAM', // __( 'Cameroon', 'woocommerce' ),
    'CA' => 'CDN', // __( 'Canada', 'woocommerce' ),
    'CV' => '', // __( 'Cape Verde', 'woocommerce' ),
    'KY' => '', // __( 'Cayman Islands', 'woocommerce' ),
    'CF' => '', // __( 'Central African Republic', 'woocommerce' ),
    'TD' => '', // __( 'Chad', 'woocommerce' ),
    'CL' => 'RCH', // __( 'Chile', 'woocommerce' ),
    'CN' => 'RC', // __( 'China', 'woocommerce' ),
    'CX' => '', // __( 'Christmas Island', 'woocommerce' ),
    'CC' => '', // __( 'Cocos (Keeling) Islands', 'woocommerce' ),
    'CO' => 'CO', // __( 'Colombia', 'woocommerce' ),
    'KM' => '', // __( 'Comoros', 'woocommerce' ),
    'CG' => '', // __( 'Congo (Brazzaville)', 'woocommerce' ),
    'CD' => '', // __( 'Congo (Kinshasa)', 'woocommerce' ),
    'CK' => '', // __( 'Cook Islands', 'woocommerce' ),
    'CR' => 'CR', // __( 'Costa Rica', 'woocommerce' ),
    'HR' => 'HR', // __( 'Croatia', 'woocommerce' ),
    'CU' => 'CU', // __( 'Cuba', 'woocommerce' ),
    'CW' => '', // __( 'Cura&ccedil;ao', 'woocommerce' ),
    'CY' => 'CY', // __( 'Cyprus', 'woocommerce' ),
    'CZ' => 'CZ', // __( 'Czech Republic', 'woocommerce' ),
    'DK' => 'DK', // __( 'Denmark', 'woocommerce' ),
    'DJ' => '', // __( 'Djibouti', 'woocommerce' ),
    'DM' => '', // __( 'Dominica', 'woocommerce' ),
    'DO' => '', // __( 'Dominican Republic', 'woocommerce' ),
    'EC' => 'EC', // __( 'Ecuador', 'woocommerce' ),
    'EG' => 'ET', // __( 'Egypt', 'woocommerce' ),
    'SV' => '', // __( 'El Salvador', 'woocommerce' ),
    'GQ' => '', // __( 'Equatorial Guinea', 'woocommerce' ),
    'ER' => '', // __( 'Eritrea', 'woocommerce' ),
    'EE' => 'EE', // __( 'Estonia', 'woocommerce' ),
    'ET' => '', // __( 'Ethiopia', 'woocommerce' ),
    'FK' => '', // __( 'Falkland Islands', 'woocommerce' ),
    'FO' => '', // __( 'Faroe Islands', 'woocommerce' ),
    'FJ' => '', // __( 'Fiji', 'woocommerce' ),
    'FI' => 'FIN', // __( 'Finland', 'woocommerce' ),
    'FR' => 'F', // __( 'France', 'woocommerce' ),
    'GF' => '', // __( 'French Guiana', 'woocommerce' ),
    'PF' => '', // __( 'French Polynesia', 'woocommerce' ),
    'TF' => '', // __( 'French Southern Territories', 'woocommerce' ),
    'GA' => '', // __( 'Gabon', 'woocommerce' ),
    'GM' => '', // __( 'Gambia', 'woocommerce' ),
    'GE' => '', // __( 'Georgia', 'woocommerce' ),
    'DE' => 'D', // __( 'Germany', 'woocommerce' ),
    'GH' => 'GH', // __( 'Ghana', 'woocommerce' ),
    'GI' => 'GBZ', // __( 'Gibraltar', 'woocommerce' ),
    'GR' => 'GR', // __( 'Greece', 'woocommerce' ),
    'GL' => '', // __( 'Greenland', 'woocommerce' ),
    'GD' => '', // __( 'Grenada', 'woocommerce' ),
    'GP' => '', // __( 'Guadeloupe', 'woocommerce' ),
    'GU' => '', // __( 'Guam', 'woocommerce' ),
    'GT' => '', // __( 'Guatemala', 'woocommerce' ),
    'GG' => '', // __( 'Guernsey', 'woocommerce' ),
    'GN' => 'GN', // __( 'Guinea', 'woocommerce' ),
    'GW' => '', // __( 'Guinea-Bissau', 'woocommerce' ),
    'GY' => '', // __( 'Guyana', 'woocommerce' ),
    'HT' => '', // __( 'Haiti', 'woocommerce' ),
    'HM' => '', // __( 'Heard Island and McDonald Islands', 'woocommerce' ),
    'HN' => '', // __( 'Honduras', 'woocommerce' ),
    'HK' => '', // __( 'Hong Kong', 'woocommerce' ),
    'HU' => 'H', // __( 'Hungary', 'woocommerce' ),
    'IS' => 'IS', // __( 'Iceland', 'woocommerce' ),
    'IN' => 'IND', // __( 'India', 'woocommerce' ),
    'ID' => 'RI', // __( 'Indonesia', 'woocommerce' ),
    'IR' => 'IR', // __( 'Iran', 'woocommerce' ),
    'IQ' => 'IRQ', // __( 'Iraq', 'woocommerce' ),
    'IE' => 'IRL', // __( 'Ireland', 'woocommerce' ),
    'IM' => '', // __( 'Isle of Man', 'woocommerce' ),
    'IL' => 'IL', // __( 'Israel', 'woocommerce' ),
    'IT' => 'I', // __( 'Italy', 'woocommerce' ),
    'CI' => 'CIV', // __( 'Ivory Coast', 'woocommerce' ),
    'JM' => 'JA', // __( 'Jamaica', 'woocommerce' ),
    'JP' => 'J', // __( 'Japan', 'woocommerce' ),
    'JE' => '', // __( 'Jersey', 'woocommerce' ),
    'JO' => '', // __( 'Jordan', 'woocommerce' ),
    'KZ' => 'KZ', // __( 'Kazakhstan', 'woocommerce' ),
    'KE' => 'EAK', // __( 'Kenya', 'woocommerce' ),
    'KI' => '', // __( 'Kiribati', 'woocommerce' ),
    'KW' => '', // __( 'Kuwait', 'woocommerce' ),
    'KG' => 'KS', // __( 'Kyrgyzstan', 'woocommerce' ),
    'LA' => '', // __( 'Laos', 'woocommerce' ),
    'LV' => 'LV', // __( 'Latvia', 'woocommerce' ),
    'LB' => 'RL', // __( 'Lebanon', 'woocommerce' ),
    'LS' => '', // __( 'Lesotho', 'woocommerce' ),
    'LR' => '', // __( 'Liberia', 'woocommerce' ),
    'LY' => '', // __( 'Libya', 'woocommerce' ),
    'LI' => 'FL', // __( 'Liechtenstein', 'woocommerce' ),
    'LT' => 'LT', // __( 'Lithuania', 'woocommerce' ),
    'LU' => 'L', // __( 'Luxembourg', 'woocommerce' ),
    'MO' => '', // __( 'Macao S.A.R., China', 'woocommerce' ),
    'MK' => 'MK', // __( 'Macedonia', 'woocommerce' ),
    'MG' => '', // __( 'Madagascar', 'woocommerce' ),
    'MW' => '', // __( 'Malawi', 'woocommerce' ),
    'MY' => 'MAL', // __( 'Malaysia', 'woocommerce' ),
    'MV' => '', // __( 'Maldives', 'woocommerce' ),
    'ML' => '', // __( 'Mali', 'woocommerce' ),
    'MT' => 'M', // __( 'Malta', 'woocommerce' ),
    'MH' => 'MH', // __( 'Marshall Islands', 'woocommerce' ),
    'MQ' => '', // __( 'Martinique', 'woocommerce' ),
    'MR' => '', // __( 'Mauritania', 'woocommerce' ),
    'MU' => '', // __( 'Mauritius', 'woocommerce' ),
    'YT' => '', // __( 'Mayotte', 'woocommerce' ),
    'MX' => 'MEX', // __( 'Mexico', 'woocommerce' ),
    'FM' => '', // __( 'Micronesia', 'woocommerce' ),
    'MD' => 'MD', // __( 'Moldova', 'woocommerce' ),
    'MC' => 'MC', // __( 'Monaco', 'woocommerce' ),
    'MN' => 'MNG', // __( 'Mongolia', 'woocommerce' ),
    'ME' => 'MNE', // __( 'Montenegro', 'woocommerce' ),
    'MS' => '', // __( 'Montserrat', 'woocommerce' ),
    'MA' => 'MA', // __( 'Morocco', 'woocommerce' ),
    'MZ' => '', // __( 'Mozambique', 'woocommerce' ),
    'MM' => '', // __( 'Myanmar', 'woocommerce' ),
    'NA' => 'NAM', // __( 'Namibia', 'woocommerce' ),
    'NR' => '', // __( 'Nauru', 'woocommerce' ),
    'NP' => 'NEP', // __( 'Nepal', 'woocommerce' ),
    'NL' => 'NL', // __( 'Netherlands', 'woocommerce' ),
    'NC' => '', // __( 'New Caledonia', 'woocommerce' ),
    'NZ' => 'NZ', // __( 'New Zealand', 'woocommerce' ),
    'NI' => '', // __( 'Nicaragua', 'woocommerce' ),
    'NE' => '', // __( 'Niger', 'woocommerce' ),
    'NG' => 'NIG', // __( 'Nigeria', 'woocommerce' ),
    'NU' => '', // __( 'Niue', 'woocommerce' ),
    'NF' => '', // __( 'Norfolk Island', 'woocommerce' ),
    'MP' => '', // __( 'Northern Mariana Islands', 'woocommerce' ),
    'KP' => 'PAT', // __( 'North Korea', 'woocommerce' ),
    'NO' => 'N', // __( 'Norway', 'woocommerce' ),
    'OM' => '', // __( 'Oman', 'woocommerce' ),
    'PK' => 'PK', // __( 'Pakistan', 'woocommerce' ),
    'PS' => '', // __( 'Palestinian Territory', 'woocommerce' ),
    'PA' => 'PA', // __( 'Panama', 'woocommerce' ),
    'PG' => 'PNG', // __( 'Papua New Guinea', 'woocommerce' ),
    'PY' => 'PY', // __( 'Paraguay', 'woocommerce' ),
    'PE' => 'PE', // __( 'Peru', 'woocommerce' ),
    'PH' => 'RP', // __( 'Philippines', 'woocommerce' ),
    'PN' => '', // __( 'Pitcairn', 'woocommerce' ),
    'PL' => 'PL', // __( 'Poland', 'woocommerce' ),
    'PT' => 'P', // __( 'Portugal', 'woocommerce' ),
    'PR' => '', // __( 'Puerto Rico', 'woocommerce' ),
    'QA' => '', // __( 'Qatar', 'woocommerce' ),
    'RE' => '', // __( 'Reunion', 'woocommerce' ),
    'RO' => 'RO', // __( 'Romania', 'woocommerce' ),
    'RU' => 'RUS', // __( 'Russia', 'woocommerce' ),
    'RW' => '', // __( 'Rwanda', 'woocommerce' ),
    'BL' => '', // __( 'Saint Barth&eacute;lemy', 'woocommerce' ),
    'SH' => '', // __( 'Saint Helena', 'woocommerce' ),
    'KN' => '', // __( 'Saint Kitts and Nevis', 'woocommerce' ),
    'LC' => '', // __( 'Saint Lucia', 'woocommerce' ),
    'MF' => '', // __( 'Saint Martin (French part)', 'woocommerce' ),
    'SX' => '', // __( 'Saint Martin (Dutch part)', 'woocommerce' ),
    'PM' => '', // __( 'Saint Pierre and Miquelon', 'woocommerce' ),
    'VC' => '', // __( 'Saint Vincent and the Grenadines', 'woocommerce' ),
    'SM' => '', // __( 'San Marino', 'woocommerce' ),
    'ST' => '', // __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'woocommerce' ),
    'SA' => 'KSA', // __( 'Saudi Arabia', 'woocommerce' ),
    'SN' => 'SEN', // __( 'Senegal', 'woocommerce' ),
    'RS' => 'SRB', // __( 'Serbia', 'woocommerce' ),
    'SC' => '', // __( 'Seychelles', 'woocommerce' ),
    'SL' => '', // __( 'Sierra Leone', 'woocommerce' ),
    'SG' => 'SGP', // __( 'Singapore', 'woocommerce' ),
    'SK' => 'SK', // __( 'Slovakia', 'woocommerce' ),
    'SI' => 'SLO', // __( 'Slovenia', 'woocommerce' ),
    'SB' => '', // __( 'Solomon Islands', 'woocommerce' ),
    'SO' => '', // __( 'Somalia', 'woocommerce' ),
    'ZA' => 'ZA', // __( 'South Africa', 'woocommerce' ),
    'GS' => '', // __( 'South Georgia/Sandwich Islands', 'woocommerce' ),
    'KR' => 'KR', // __( 'South Korea', 'woocommerce' ),
    'SS' => '', // __( 'South Sudan', 'woocommerce' ),
    'ES' => 'E', // __( 'Spain', 'woocommerce' ),
    'LK' => 'CL', // __( 'Sri Lanka', 'woocommerce' ),
    'SD' => 'SUD', // __( 'Sudan', 'woocommerce' ),
    'SR' => '', // __( 'Suriname', 'woocommerce' ),
    'SJ' => '', // __( 'Svalbard and Jan Mayen', 'woocommerce' ),
    'SZ' => '', // __( 'Swaziland', 'woocommerce' ),
    'SE' => 'S', // __( 'Sweden', 'woocommerce' ),
    'CH' => 'CH', // __( 'Switzerland', 'woocommerce' ),
    'SY' => 'SYR', // __( 'Syria', 'woocommerce' ),
    'TW' => '', // __( 'Taiwan', 'woocommerce' ),
    'TJ' => '', // __( 'Tajikistan', 'woocommerce' ),
    'TZ' => 'EAT', // __( 'Tanzania', 'woocommerce' ),
    'TH' => 'T', // __( 'Thailand', 'woocommerce' ),
    'TL' => '', // __( 'Timor-Leste', 'woocommerce' ),
    'TG' => 'RT', // __( 'Togo', 'woocommerce' ),
    'TK' => '', // __( 'Tokelau', 'woocommerce' ),
    'TO' => '', // __( 'Tonga', 'woocommerce' ),
    'TT' => '', // __( 'Trinidad and Tobago', 'woocommerce' ),
    'TN' => 'TN', // __( 'Tunisia', 'woocommerce' ),
    'TR' => 'TR', // __( 'Turkey', 'woocommerce' ),
    'TM' => '', // __( 'Turkmenistan', 'woocommerce' ),
    'TC' => '', // __( 'Turks and Caicos Islands', 'woocommerce' ),
    'TV' => '', // __( 'Tuvalu', 'woocommerce' ),
    'UG' => '', // __( 'Uganda', 'woocommerce' ),
    'UA' => 'UA', // __( 'Ukraine', 'woocommerce' ),
    'AE' => 'UAE', // __( 'United Arab Emirates', 'woocommerce' ),
    'GB' => 'GB', // __( 'United Kingdom (UK)', 'woocommerce' ),
    'US' => 'USA', // __( 'United States (US)', 'woocommerce' ),
    'UM' => '', // __( 'United States (US) Minor Outlying Islands', 'woocommerce' ),
    'VI' => '', // __( 'United States (US) Virgin Islands', 'woocommerce' ),
    'UY' => 'ROU', // __( 'Uruguay', 'woocommerce' ),
    'UZ' => 'UZ', // __( 'Uzbekistan', 'woocommerce' ),
    'VU' => '', // __( 'Vanuatu', 'woocommerce' ),
    'VA' => '', // __( 'Vatican', 'woocommerce' ),
    'VE' => '', // __( 'Venezuela', 'woocommerce' ),
    'VN' => 'VN', // __( 'Vietnam', 'woocommerce' ),
    'WF' => '', // __( 'Wallis and Futuna', 'woocommerce' ),
    'EH' => '', // __( 'Western Sahara', 'woocommerce' ),
    'WS' => '', // __( 'Samoa', 'woocommerce' ),
    'YE' => '', // __( 'Yemen', 'woocommerce' ),
    'ZM' => '', // __( 'Zambia', 'woocommerce' ),
    'ZW' => 'ZW', // __( 'Zimbabwe', 'woocommerce' ),
  ];

  /**
   * Returns the alfa country vehicle code (if any) for a given ISO country code.
   *
   * @param string $iso_code
   *   The ISO country code to lookup.
   *
   * @return string
   */
  public static function toAlfa(string $iso_code) {
    return !empty(static::MAP[$iso_code]) ? static::MAP[$iso_code] : $iso_code;
  }

  /**
   * Returns the ISO country code (if any) for a given alfa country vehicle code.
   *
   * @param string $alfa_code
   *   The alfa country vehicle code to lookup.
   *
   * @return string
   */
  public static function toIso(string $alfa_code) {
    return array_search($alfa_code, static::MAP, TRUE) ?: $alfa_code;
  }

}
